name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_REPO_NAME
      env:
        DOCKER_IMAGE_REPO_NAME: ${{ vars.DOCKER_IMAGE_REPO_NAME }}
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image to DockerHub
      run: docker push $DOCKER_IMAGE_REPO_NAME
      env:
        DOCKER_IMAGE_REPO_NAME: ${{ vars.DOCKER_IMAGE_REPO_NAME }}